### ISSUE TITLE
Compilation error with GCC 10.2 on Debian ARM

### ISSUE THREAD

**Issue by culyzhao** [google/mount-zip#27] opened 2024-10-13 04:48 UTC
Openmediavault 6.3.11-2 (Shaitan)
Linux 5.15.93-rockchip64

```
g++ -Ilib -c  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -pedantic -std=c++20 -O2 -DNDEBUG main.cc -o main.o
In file included from lib/error.h:26,
                 from main.cc:42:
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[3], int&, const char (&)[2]}; std::string = std::__cxx11::basic_string<char>]’:
main.cc:505:49:   required from here
lib/log.h:29:68: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
   29 |   return (std::ostringstream() << ... << std::forward<Args>(args)).str();
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[22], Path}; std::string = std::__cxx11::basic_string<char>]’:
lib/error.h:77:33:   required from ‘void ThrowSystemError(Args&& ...) [with Args = {const char (&)[22], Path}]’
main.cc:458:70:   required from here
lib/log.h:29:68: error: ‘std::ostream’ {aka ‘class std::basic_ostream<char>’} has no member named ‘str’
make: *** [Makefile:52: main.o] Error 1
```

fix lib/log.h as below resolve the error.
```
std::string StrCat(Args&&... args) {
    std::ostringstream stream;
    (stream << ... << std::forward<Args>(args));
    return stream.str();
}
```

**Comment by fdegros** [comment] 2024-10-13 23:29
Thanks for the report.

Please try again with the latest sources, and let me know if this is working or not.

**Comment by culyzhao** [comment] 2024-10-14 03:00
still has same error
···
root@nanopim4v2:~/mount-zip# make
g++ -Ilib -c  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -pedantic -std=c++20 -O2 -DNDEBUG main.cc -o main.o
In file included from lib/error.h:26,
                 from main.cc:42:
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[3], int&, const char (&)[2]}; std::string = std::__cxx11::basic_string<char>]’:
main.cc:505:49:   required from here
lib/log.h:30:68: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
   30 |   return (std::ostringstream() << ... << std::forward<Args>(args)).str();
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[22], Path}; std::string = std::__cxx11::basic_string<char>]’:
lib/error.h:77:33:   required from ‘void ThrowSystemError(Args&& ...) [with Args = {const char (&)[22], Path}]’
main.cc:458:70:   required from here
lib/log.h:30:68: error: ‘std::ostream’ {aka ‘class std::basic_ostream<char>’} has no member named ‘str’
make: *** [Makefile:49: main.o] Error 1

root@nanopim4v2:~/mount-zip# cat ./lib/log.h | grep ostream
#include <ostream>
  friend std::ostream& operator<<(std::ostream& out, const Timer& timer) {
···

**Comment by fdegros** [comment] 2024-10-14 03:20
Can you try to run `make clean` before running `make` again? Does it change anything?

Which versions of the C++ compiler and standard library are you using?

This is really strange. It looks like your C++ standard library does not provide the expected `operator<<` for `basic_ostream` rvalue, which has been added to C++11. See point (3) [here](http://go/cppref/cpp/io/basic_ostream/operator_ltlt2).

**Comment by culyzhao** [comment] 2024-10-14 05:55
Yes, I cleaned. I also cloned a new folder, no change.
```
root@nanopim4v2:~/mount-zip# make clean
make -C lib clean
make[1]: Entering directory '/root/mount-zip/lib'
rm -f libmountzip.a data_node.o extra_field.o log.o path.o reader.o scoped_file.o tree.o
make[1]: Leaving directory '/root/mount-zip/lib'
rm -f main.o mount-zip
make -C tests clean
make[1]: Entering directory '/root/mount-zip/tests'
make -C whitebox clean
make[2]: Entering directory '/root/mount-zip/tests/whitebox'
make -C ../../lib clean
make[3]: Entering directory '/root/mount-zip/lib'
rm -f libmountzip.a data_node.o extra_field.o log.o path.o reader.o scoped_file.o tree.o
make[3]: Leaving directory '/root/mount-zip/lib'
rm -f *.x.core vgcore.*
rm -f *.o extra_field_test.x filename_validator.x zip_bad_structure.x zip_open_failure.x extra_field_test.o filename_validator.o zip_bad_structure.o zip_open_failure.o
make[2]: Leaving directory '/root/mount-zip/tests/whitebox'
make[1]: Leaving directory '/root/mount-zip/tests'
root@nanopim4v2:~/mount-zip# make
g++ -Ilib -c  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -pedantic -std=c++20 -O2 -DNDEBUG main.cc -o main.o
In file included from lib/error.h:26,
                 from main.cc:42:
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[3], int&, const char (&)[2]}; std::string = std::__cxx11::basic_string<char>]’:
main.cc:505:49:   required from here
lib/log.h:30:68: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
   30 |   return (std::ostringstream() << ... << std::forward<Args>(args)).str();
lib/log.h: In instantiation of ‘std::string StrCat(Args&& ...) [with Args = {const char (&)[22], Path}; std::string = std::__cxx11::basic_string<char>]’:
lib/error.h:77:33:   required from ‘void ThrowSystemError(Args&& ...) [with Args = {const char (&)[22], Path}]’
main.cc:458:70:   required from here
lib/log.h:30:68: error: ‘std::ostream’ {aka ‘class std::basic_ostream<char>’} has no member named ‘str’
make: *** [Makefile:49: main.o] Error 1
```
version information
```
root@nanopim4v2:~/mount-zip# g++
g++: fatal error: no input files
compilation terminated.
root@nanopim4v2:~/mount-zip# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/10/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
root@nanopim4v2:~/mount-zip# apt-cache search -n libstdc++
libstdc++-10-dev - GNU Standard C++ Library v3 (development files)
libstdc++-10-doc - GNU Standard C++ Library v3 (documentation files)
libstdc++-10-pic - GNU Standard C++ Library v3 (shared library subset kit)
libstdc++6 - GNU Standard C++ Library v3
libstdc++6-10-dbg - GNU Standard C++ Library v3 (debug build)
libstdc++-10-dev-amd64-cross - GNU Standard C++ Library v3 (development files) (amd64)
libstdc++-10-dev-arm64-cross - GNU Standard C++ Library v3 (development files) (arm64)
libstdc++-10-dev-armel-cross - GNU Standard C++ Library v3 (development files) (armel)
libstdc++-10-dev-armhf-cross - GNU Standard C++ Library v3 (development files) (armhf)
libstdc++-10-dev-i386-cross - GNU Standard C++ Library v3 (development files) (i386)
libstdc++-10-dev-ppc64el-cross - GNU Standard C++ Library v3 (development files) (ppc64el)
libstdc++-10-dev-s390x-cross - GNU Standard C++ Library v3 (development files) (s390x)
libstdc++-10-pic-amd64-cross - GNU Standard C++ Library v3 (shared library subset kit) (amd64)
libstdc++-10-pic-arm64-cross - GNU Standard C++ Library v3 (shared library subset kit) (arm64)
libstdc++-10-pic-armel-cross - GNU Standard C++ Library v3 (shared library subset kit) (armel)
libstdc++-10-pic-armhf-cross - GNU Standard C++ Library v3 (shared library subset kit) (armhf)
libstdc++-10-pic-i386-cross - GNU Standard C++ Library v3 (shared library subset kit) (i386)
libstdc++-10-pic-ppc64el-cross - GNU Standard C++ Library v3 (shared library subset kit) (ppc64el)
libstdc++-10-pic-s390x-cross - GNU Standard C++ Library v3 (shared library subset kit) (s390x)
libstdc++6-amd64-cross - GNU Standard C++ Library v3 (amd64)
libstdc++6-arm64-cross - GNU Standard C++ Library v3 (arm64)
libstdc++6-armel-cross - GNU Standard C++ Library v3 (armel)
libstdc++6-armhf-cross - GNU Standard C++ Library v3 (armhf)
libstdc++6-i386-cross - GNU Standard C++ Library v3 (i386)
libstdc++6-ppc64el-cross - GNU Standard C++ Library v3 (ppc64el)
libstdc++6-s390x-cross - GNU Standard C++ Library v3 (s390x)
libstdc++-10-dev-mips-cross - GNU Standard C++ Library v3 (development files) (mips)
libstdc++-10-dev-mips64-cross - GNU Standard C++ Library v3 (development files) (mips64)
libstdc++-10-dev-mips64el-cross - GNU Standard C++ Library v3 (development files) (mips64el)
libstdc++-10-dev-mips64r6-cross - GNU Standard C++ Library v3 (development files) (mips64r6)
libstdc++-10-dev-mips64r6el-cross - GNU Standard C++ Library v3 (development files) (mips64r6el)
libstdc++-10-dev-mipsel-cross - GNU Standard C++ Library v3 (development files) (mipsel)
libstdc++-10-dev-mipsr6-cross - GNU Standard C++ Library v3 (development files) (mipsr6)
libstdc++-10-dev-mipsr6el-cross - GNU Standard C++ Library v3 (development files) (mipsr6el)
libstdc++-10-pic-mips-cross - GNU Standard C++ Library v3 (shared library subset kit) (mips)
libstdc++-10-pic-mips64-cross - GNU Standard C++ Library v3 (shared library subset kit) (mips64)
libstdc++-10-pic-mips64el-cross - GNU Standard C++ Library v3 (shared library subset kit) (mips64el)
libstdc++-10-pic-mips64r6-cross - GNU Standard C++ Library v3 (shared library subset kit) (mips64r6)
libstdc++-10-pic-mips64r6el-cross - GNU Standard C++ Library v3 (shared library subset kit) (mips64r6el)
libstdc++-10-pic-mipsel-cross - GNU Standard C++ Library v3 (shared library subset kit) (mipsel)
libstdc++-10-pic-mipsr6-cross - GNU Standard C++ Library v3 (shared library subset kit) (mipsr6)
libstdc++-10-pic-mipsr6el-cross - GNU Standard C++ Library v3 (shared library subset kit) (mipsr6el)
libstdc++6-mips-cross - GNU Standard C++ Library v3 (mips)
libstdc++6-mips64-cross - GNU Standard C++ Library v3 (mips64)
libstdc++6-mips64el-cross - GNU Standard C++ Library v3 (mips64el)
libstdc++6-mips64r6-cross - GNU Standard C++ Library v3 (mips64r6)
libstdc++6-mips64r6el-cross - GNU Standard C++ Library v3 (mips64r6el)
libstdc++6-mipsel-cross - GNU Standard C++ Library v3 (mipsel)
libstdc++6-mipsr6-cross - GNU Standard C++ Library v3 (mipsr6)
libstdc++6-mipsr6el-cross - GNU Standard C++ Library v3 (mipsr6el)
libstdc++-10-dev-alpha-cross - GNU Standard C++ Library v3 (development files) (alpha)
libstdc++-10-dev-hppa-cross - GNU Standard C++ Library v3 (development files) (hppa)
libstdc++-10-dev-m68k-cross - GNU Standard C++ Library v3 (development files) (m68k)
libstdc++-10-dev-powerpc-cross - GNU Standard C++ Library v3 (development files) (powerpc)
libstdc++-10-dev-ppc64-cross - GNU Standard C++ Library v3 (development files) (ppc64)
libstdc++-10-dev-riscv64-cross - GNU Standard C++ Library v3 (development files) (riscv64)
libstdc++-10-dev-sh4-cross - GNU Standard C++ Library v3 (development files) (sh4)
libstdc++-10-dev-sparc64-cross - GNU Standard C++ Library v3 (development files) (sparc64)
libstdc++-10-dev-x32-cross - GNU Standard C++ Library v3 (development files) (x32)
libstdc++-10-pic-alpha-cross - GNU Standard C++ Library v3 (shared library subset kit) (alpha)
libstdc++-10-pic-hppa-cross - GNU Standard C++ Library v3 (shared library subset kit) (hppa)
libstdc++-10-pic-m68k-cross - GNU Standard C++ Library v3 (shared library subset kit) (m68k)
libstdc++-10-pic-powerpc-cross - GNU Standard C++ Library v3 (shared library subset kit) (powerpc)
libstdc++-10-pic-ppc64-cross - GNU Standard C++ Library v3 (shared library subset kit) (ppc64)
libstdc++-10-pic-riscv64-cross - GNU Standard C++ Library v3 (shared library subset kit) (riscv64)
libstdc++-10-pic-sh4-cross - GNU Standard C++ Library v3 (shared library subset kit) (sh4)
libstdc++-10-pic-sparc64-cross - GNU Standard C++ Library v3 (shared library subset kit) (sparc64)
libstdc++-10-pic-x32-cross - GNU Standard C++ Library v3 (shared library subset kit) (x32)
libstdc++6-alpha-cross - GNU Standard C++ Library v3 (alpha)
libstdc++6-hppa-cross - GNU Standard C++ Library v3 (hppa)
libstdc++6-m68k-cross - GNU Standard C++ Library v3 (m68k)
libstdc++6-powerpc-cross - GNU Standard C++ Library v3 (powerpc)
libstdc++6-ppc64-cross - GNU Standard C++ Library v3 (ppc64)
libstdc++6-riscv64-cross - GNU Standard C++ Library v3 (riscv64)
libstdc++6-sh4-cross - GNU Standard C++ Library v3 (sh4)
libstdc++6-sparc64-cross - GNU Standard C++ Library v3 (sparc64)
libstdc++6-x32-cross - GNU Standard C++ Library v3 (x32)
libstdc++-9-dev - GNU Standard C++ Library v3 (development files)
libstdc++-9-doc - GNU Standard C++ Library v3 (documentation files)
libstdc++-9-pic - GNU Standard C++ Library v3 (shared library subset kit)
libstdc++6-9-dbg - GNU Standard C++ Library v3 (debug build)
libstdc++-9-dev-amd64-cross - GNU Standard C++ Library v3 (development files) (amd64)
libstdc++-9-dev-arm64-cross - GNU Standard C++ Library v3 (development files) (arm64)
libstdc++-9-dev-armel-cross - GNU Standard C++ Library v3 (development files) (armel)
libstdc++-9-dev-armhf-cross - GNU Standard C++ Library v3 (development files) (armhf)
libstdc++-9-dev-i386-cross - GNU Standard C++ Library v3 (development files) (i386)
libstdc++-9-dev-ppc64el-cross - GNU Standard C++ Library v3 (development files) (ppc64el)
libstdc++-9-dev-s390x-cross - GNU Standard C++ Library v3 (development files) (s390x)
libstdc++-9-pic-amd64-cross - GNU Standard C++ Library v3 (shared library subset kit) (amd64)
libstdc++-9-pic-arm64-cross - GNU Standard C++ Library v3 (shared library subset kit) (arm64)
libstdc++-9-pic-armel-cross - GNU Standard C++ Library v3 (shared library subset kit) (armel)
libstdc++-9-pic-armhf-cross - GNU Standard C++ Library v3 (shared library subset kit) (armhf)
libstdc++-9-pic-i386-cross - GNU Standard C++ Library v3 (shared library subset kit) (i386)
libstdc++-9-pic-ppc64el-cross - GNU Standard C++ Library v3 (shared library subset kit) (ppc64el)
libstdc++-9-pic-s390x-cross - GNU Standard C++ Library v3 (shared library subset kit) (s390x)
libstdc++-9-dev-alpha-cross - GNU Standard C++ Library v3 (development files) (alpha)
libstdc++-9-dev-hppa-cross - GNU Standard C++ Library v3 (development files) (hppa)
libstdc++-9-dev-m68k-cross - GNU Standard C++ Library v3 (development files) (m68k)
libstdc++-9-dev-powerpc-cross - GNU Standard C++ Library v3 (development files) (powerpc)
libstdc++-9-dev-ppc64-cross - GNU Standard C++ Library v3 (development files) (ppc64)
libstdc++-9-dev-riscv64-cross - GNU Standard C++ Library v3 (development files) (riscv64)
libstdc++-9-dev-sh4-cross - GNU Standard C++ Library v3 (development files) (sh4)
libstdc++-9-dev-sparc64-cross - GNU Standard C++ Library v3 (development files) (sparc64)
libstdc++-9-dev-x32-cross - GNU Standard C++ Library v3 (development files) (x32)
libstdc++-9-pic-alpha-cross - GNU Standard C++ Library v3 (shared library subset kit) (alpha)
libstdc++-9-pic-hppa-cross - GNU Standard C++ Library v3 (shared library subset kit) (hppa)
libstdc++-9-pic-m68k-cross - GNU Standard C++ Library v3 (shared library subset kit) (m68k)
libstdc++-9-pic-powerpc-cross - GNU Standard C++ Library v3 (shared library subset kit) (powerpc)
libstdc++-9-pic-ppc64-cross - GNU Standard C++ Library v3 (shared library subset kit) (ppc64)
libstdc++-9-pic-riscv64-cross - GNU Standard C++ Library v3 (shared library subset kit) (riscv64)
libstdc++-9-pic-sh4-cross - GNU Standard C++ Library v3 (shared library subset kit) (sh4)
libstdc++-9-pic-sparc64-cross - GNU Standard C++ Library v3 (shared library subset kit) (sparc64)
libstdc++-9-pic-x32-cross - GNU Standard C++ Library v3 (shared library subset kit) (x32)
libstdc++-arm-none-eabi-newlib - GNU Standard C++ Library v3 for ARM Cortex-R/M processors (newlib)
libstdcompat-ocaml - compatibility module for OCaml standard library (runtime)
libstdcompat-ocaml-dev - compatibility module for OCaml standard library (development)
```

**Comment by fdegros** [comment] 2024-10-14 22:30
It seems that you have several versions of `libstdc++` on your system, but I cannot tell which one is getting used by your `g++` compiler. Also, your version of `g++` (10.2.1) does not seem to be one of the most recent versions. Maybe that plays a role in the issue.

On my system, I have:

```
$ g++ --version
g++ (Debian 13.2.0-13) 13.2.0
```

Can you try compiling the following test program?

```
$ cat > hi.cc <<EOF
#include <iostream>
#include <sstream>
#include <string>

int main() {
  std::string s = (std::ostringstream() << "Hi there!").str();
  std::cout << s << "\n";
}
EOF

$ g++ -std=c++20 hi.cc -o hi && ./hi
Hi there!
```

It should even compile in C++11 mode:

```
$ g++ -std=c++11 hi.cc -o hi && ./hi
Hi there!
```

But not in C++98 mode:

```
$ g++ -std=c++98 hi.cc -o hi && ./hi
hi.cc: In function ‘int main()’:
hi.cc:6:57: error: ‘std::basic_ostream<char>::__ostream_type’ {aka ‘class std::basic_ostream<char>’} has no member named ‘str’
    6 |   std::string s = (std::ostringstream() << "Hi there!").str();
      |                                                         ^~~
```

What do you get on your system?

**Comment by culyzhao** [comment] 2024-10-15 15:18
It is Detian Bullseye's problem, it come with gcc 10.2 and no default suport for 11+.
I use  Armbian 23.02.2 Bullseye with Linux 5.15.93-rockchip64, the workaround "std::ostringstream stream;..." worked very well, so I don't want to manually download and install missing dependencies for gcc 11.

```
root@nanopim4v2:~# g++ -std=c++20 hi.cc -o hi && ./hi
hi.cc: In function ‘int main()’:
hi.cc:6:57: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
    6 |   std::string s = (std::ostringstream() << "Hi there!").str();
      |                                                         ^~~
root@nanopim4v2:~# g++ -std=c++11 hi.cc -o hi && ./hi
hi.cc: In function ‘int main()’:
hi.cc:6:57: error: ‘class std::basic_ostream<char>’ has no member named ‘str’
    6 |   std::string s = (std::ostringstream() << "Hi there!").str();
      |                                                         ^~~
root@nanopim4v2:~# g++ -std=c++98 hi.cc -o hi && ./hi
hi.cc: In function ‘int main()’:
hi.cc:6:57: error: ‘std::basic_ostream<char>::__ostream_type’ {aka ‘class std::basic_ostream<char>’} has no member named ‘str’
    6 |   std::string s = (std::ostringstream() << "Hi there!").str();
      |                                                         ^~~
root@nanopim4v2:~# cat hi.cc
#include <iostream>
#include <sstream>
#include <string>

int main() {
  std::string s = (std::ostringstream() << "Hi there!").str();
  std::cout << s << "\n";
}
```

**Comment by fdegros** [comment] 2024-10-15 23:50
Thanks for the confirmation.

Your C++ compiler (gcc 10.2.1) does not support a common C++11 feature, even though it accepts the `-std=c++11` and `-std=c++20` command-line arguments enabling the C++11 and C++20 modes.

**Comment by fdegros** [comment] 2024-10-16 03:11
I'm going to close this issue. The cause of this issue is now understood, and you have a workaround for the systems where you cannot upgrade the C++ compiler.

**Closed by fdegros** 2024-10-16 03:11 UTC

**Comment by fdegros** [comment] 2024-11-29 04:29
Should be fixed now.
